services:
  - type: web
    name: dovebot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
    - key: NODE_ENV
      value: production
    - key: GROQ_API_KEY
      sync: false